[tools]
node = "24"
python = "3.12"
helix = "latest"
tmux = "3.6a"
lazygit = "latest"
uv = "latest"
fzf = "latest"
rg = "latest"
jq = "latest"
fd = "latest"
bat = "latest"
yq = "latest"
shellcheck = "latest"
