[tools]
node = "24.13.1"
python = "3.12.12"
helix = "25.07.1"
tmux = "3.6a"
lazygit = "0.59.0"
uv = "0.10.4"
fzf = "0.68.0"
rg = "15.1.0"
jq = "1.8.1"
fd = "10.3.0"
bat = "0.26.1"
yq = "4.52.4"
shellcheck = "0.11.0"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.20.0"
"npm:prettier" = "3.8.1"
