theme = "darcula-solid"

[keys.normal]
D = "kill_to_line_end"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"

[editor]
default-yank-register = "+"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
