gui:
  theme:
    activeBorderColor:
      - "#00D4FF"
      - bold
    inactiveBorderColor:
      - "#8EA0B4"
    searchingActiveBorderColor:
      - "#FFEF5A"
      - bold
    optionsTextColor:
      - "#C77DFF"
    selectedLineBgColor:
      - "#00253F"
    selectedRangeBgColor:
      - "#003255"
    cherryPickedCommitFgColor:
      - "#4DFF88"
    markedBaseCommitFgColor:
      - "#FFB347"
    unstagedChangesColor:
      - "#FF3B3B"
    defaultFgColor:
      - "#FFFFFF"
