gui:
  theme:
    activeBorderColor:
      - "#cc7832" # orange
      - bold
    inactiveBorderColor:
      - "#555555"
    searchingActiveBorderColor:
      - "#eedd82"
      - bold
    optionsTextColor:
      - "#9876aa"
    selectedLineBgColor:
      - "#323232"
    selectedRangeBgColor:
      - "#3a3a3a"
    cherryPickedCommitFgColor:
      - "#32cd32"
    markedBaseCommitFgColor:
      - "#eedd82"
    unstagedChangesColor:
      - "#ff6b68"
    defaultFgColor:
      - "#d8d8d8"
